"""Initial migration

Revision ID: 330de1d3c151
Revises: 
Create Date: 2025-07-01 21:26:54.762137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330de1d3c151'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_prerequisites', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_prerequisites', 'courses', ['prerequisite_id'], ['id'])
    op.create_foreign_key(None, 'course_student', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'course_student', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_tags', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'lesson_completions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'lesson_completions', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'modules', ['module_id'], ['id'])
    op.create_foreign_key(None, 'modules', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'quiz_options', 'quiz_questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'user_quiz_results', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_quiz_results', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'user_recommendations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_recommendations', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'user_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'user_quiz_results', type_='foreignkey')
    op.drop_constraint(None, 'user_quiz_results', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_constraint(None, 'quiz_options', type_='foreignkey')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    op.drop_constraint(None, 'lesson_completions', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'course_tags', type_='foreignkey')
    op.drop_constraint(None, 'course_tags', type_='foreignkey')
    op.drop_constraint(None, 'course_student', type_='foreignkey')
    op.drop_constraint(None, 'course_student', type_='foreignkey')
    op.drop_constraint(None, 'course_prerequisites', type_='foreignkey')
    op.drop_constraint(None, 'course_prerequisites', type_='foreignkey')
    # ### end Alembic commands ###
